-- db_sett_oversea.t_channel_month_plt_income  | 账单报表-平台费
USE db_sett_oversea;
DROP TABLE IF EXISTS t_channel_month_plt_income;
CREATE TABLE `t_channel_month_plt_income` (
  `Fid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `Fsett_month` varchar(10) NOT NULL DEFAULT '' COMMENT '结算月份',
  `Fbill_month` varchar(10) NOT NULL DEFAULT '' COMMENT '账单月份',
  `Fdata_month` varchar(10) NOT NULL DEFAULT '' COMMENT '数据月份',
  `Fdata_date` varchar(10) NOT NULL DEFAULT '' COMMENT '数据日期',
  `Fchannel_id` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 渠道ID',
  `Fchannel_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 渠道名称',
  `Fchannel_ims` varchar(100) NOT NULL DEFAULT '' COMMENT '推送IMS渠道名称',
  `Fsubchannel_id` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 子渠道ID',
  `Fsubchannel_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 子渠道',
  `Fsett_type` varchar(255) NOT NULL DEFAULT '' COMMENT '结算维度',
  `Fbilling_type` varchar(32) NOT NULL DEFAULT '' COMMENT '计费模式',
  `Fplt_fee_type` varchar(64) NOT NULL DEFAULT '' COMMENT '平台费类型',
  `Fmdm_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户MDMID',
  `Fmdm_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户MDM名称',
  `Fchannel_mdm_id` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道MDMID',
  `Fchannel_mdm_name` varchar(256) NOT NULL DEFAULT '' COMMENT '渠道MDM名称',
  `Fbiz_customer_no` varchar(32) NOT NULL DEFAULT '' COMMENT '业务客户代码',
  `Fbiz_customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '业务客户名称',
  `Fmerchant_type` varchar(32) NOT NULL DEFAULT '' COMMENT '商户类型',
  `Fmerchant_mdm_id` varchar(32) NOT NULL DEFAULT '' COMMENT '商户MDMID',
  `Fmerchant_mdm_name` varchar(256) NOT NULL DEFAULT '' COMMENT '商户MDM名称',
  `Ficp_code` varchar(32) NOT NULL DEFAULT '' COMMENT 'ICP编号',
  `Ficp_name` varchar(128) NOT NULL DEFAULT '' COMMENT 'ICP名称',
  `Fou_id` int(10) NOT NULL DEFAULT '0' COMMENT '我方主体ID',
  `Fou_name` varchar(100) NOT NULL DEFAULT '' COMMENT '我方主体名称',
  `Fou_name_short` varchar(128) DEFAULT '' COMMENT 'OU简称',
  `Fproduct_no` varchar(64) NOT NULL DEFAULT '' COMMENT '产品编号',
  `Fproduct_name` varchar(128) NOT NULL DEFAULT '' COMMENT '产品名称',
  `Foffer_id` varchar(64) NOT NULL DEFAULT '' COMMENT '应用ID',
  `Foffer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '应用名称',
  `Fspoa_id` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS SPOA ID',
  `Fspoa_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS SPOA名称',
  `Fsett_group` varchar(20) NOT NULL DEFAULT '' COMMENT '结算组ID',
  `Fsett_group_name` varchar(128) DEFAULT '' COMMENT '结算组名称',
  `Fbusi_group` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 业务组ID',
  `Fbusi_group_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 业务组名称',
  `Fdept` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 部门ID',
  `Fdept_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 部门名称',
  `Fcountry` varchar(100) NOT NULL DEFAULT '' COMMENT '国别/地区',
  `Fori_currency` varchar(20) NOT NULL DEFAULT '' COMMENT '原始币种',
  `Fori_income` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '计费金额（原始币种）',
  `Fori_plt_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台费率',
  `Fori_plt_amount` double(20,4) DEFAULT NULL COMMENT '平台费（原始币种）',
  `Fori_tax_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '税率',
  `Fori_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '税费（原始币种）',
  `Fori_plt_tax_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台代缴税率',
  `Fori_plt_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台代缴税（原始币种）',
  `Fori_channel_tax_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道代缴税率',
  `Fori_channel_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道代缴税（原始币种）',
  `Fori_channel_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道费率',
  `Fori_channel_amount` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道费（原始币种）',
  `Fori_refund` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '退款金额（原始币种）',
  `Fori_settlement` double(20,4) DEFAULT NULL COMMENT '结算金额（原始币种）',
  `Fchannel_rule_type` varchar(64) NOT NULL DEFAULT '' COMMENT '渠道规则类型',
  `Fori_channel_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道费用总额（原始币种）',
  `Fori_channel_percent_fee_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道固定比例费率（原始币种）',
  `Fori_channel_percent_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道固定比例费总额（原始币种）',
  `Fori_channel_per_transaction_fee` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道每笔交易费（原始币种）',
  `Fori_channel_per_transaction_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道每笔交易费总额（原始币种）',
  `Fori_channel_per_transaction_min_fee` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道每笔最小收费（原始币种）',
  `Fori_channel_per_transaction_min_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道每笔最小收费总额（原始币种）',
  `Fori_channel_installment_fee_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道分期费率（原始币种）',
  `Fori_channel_installment_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道分期费总额（原始币种）',
  `Fori_channel_ot_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道其他费用总额（原始币种）',
  `Fmerchant_rule_type` varchar(64) NOT NULL DEFAULT '' COMMENT '商户规则类型',
  `Fori_merchant_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户费用总额（原始币种）',
  `Fori_merchant_percent_fee_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户固定比例费率（原始币种）',
  `Fori_merchant_percent_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户固定比例费总额（原始币种）',
  `Fori_merchant_per_transaction_fee` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户每笔交易费（原始币种）',
  `Fori_merchant_per_transaction_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户每笔交易费总额（原始币种）',
  `Fori_merchant_per_transaction_min_fee` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户每笔最小收费（原始币种）',
  `Fori_merchant_per_transaction_min_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户每笔最小收费总额（原始币种）',
  `Fori_merchant_installment_fee_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户分期费率（原始币种）',
  `Fori_merchant_installment_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户分期费总额（原始币种）',
  `Fori_merchant_ot_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '商户其他费用总额（原始币种）',
  `Fori_plt_fee_total` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台手续费总额（原始币种）',
  `Fori_sett_currency_rate` double(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '原币兑结算币种汇率',
  `Fsett_currency` varchar(20) NOT NULL DEFAULT '' COMMENT '结算币种',
  `Fsett_income` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '计费金额（结算币种）',
  `Fsett_plt_amount` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台费（结算币种）',
  `Fsett_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '税费（结算币种）',
  `Fsett_plt_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台代缴税（结算币种）',
  `Fsett_channel_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道代缴税（结算币种）',
  `Fsett_channel_amount` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道费（结算币种）',
  `Fsett_refund` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '退款金额（结算币种）',
  `Fsett_settlement` double(20,4) DEFAULT NULL COMMENT '结算金额（结算币种）',
  `Fsett_rmb_currency_rate` double(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '结算币种兑人民币汇率',
  `Frmb_income` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '计费金额（人民币）',
  `Frmb_plt_amount` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台费（人民币）',
  `Frmb_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '税费（人民币）',
  `Frmb_plt_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '平台代缴税（人民币）',
  `Frmb_channel_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道代缴税（人民币）',
  `Frmb_channel_amount` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '渠道费（人民币）',
  `Frmb_refund` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '退款金额（人民币）',
  `Frmb_settlement` double(20,4) DEFAULT NULL COMMENT '结算金额（人民币）',
  `Fims_channel_id` varchar(100) NOT NULL DEFAULT '' COMMENT 'IMS渠道ID',
  `Fims_channel_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'IMS渠道名称',
  `Fcontract_no` varchar(128) NOT NULL DEFAULT '' COMMENT '合同号(废弃)',
  `Fchannel_contract_no` varchar(128) NOT NULL DEFAULT '' COMMENT '渠道合同号',
  `Fmerchant_contract_no` varchar(128) NOT NULL DEFAULT '' COMMENT '商户合同号',
  `Fdata_source_no` varchar(128) NOT NULL DEFAULT '' COMMENT '数据来源编号',
  `Fdata_source_name` varchar(128) NOT NULL DEFAULT '' COMMENT '数据来源名称',
  `Fapproval_status` varchar(16) NOT NULL DEFAULT '1' COMMENT '审核状态（1未审批  2 审批中 3审批通过 4审批驳回）',
  `Fapproval_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '审批原因',
  `Fmodify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`Fid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
