-- db_mpay_income.t_boss_channel_bill  | 账单报表-BOSS海外渠道账单收入
USE db_mpay_income;
DROP TABLE IF EXISTS t_boss_channel_bill;
CREATE TABLE `t_boss_channel_bill` (
  `Fid` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `Fbill_type` varchar(64) NOT NULL DEFAULT '' COMMENT '账单类型（PLATFORM、MERCHANT）',
  `Fsett_month` varchar(10) NOT NULL DEFAULT '' COMMENT '结算月份',
  `Fbill_month` varchar(10) NOT NULL DEFAULT '' COMMENT '账单月份',
  `Fchannel_id` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 渠道ID',
  `Fchannel_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 渠道名称',
  `Fsubchannel_id` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 子渠道ID',
  `Fsubchannel_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 子渠道',
  `Fsett_type` varchar(255) NOT NULL DEFAULT '' COMMENT '结算维度',
  `Fbilling_type` varchar(32) NOT NULL DEFAULT '' COMMENT '计费模式',
  `Fmerchant_type` varchar(32) NOT NULL DEFAULT '' COMMENT '商户类型',
  `Fmdm_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户MDMID',
  `Fmdm_name` varchar(128) NOT NULL DEFAULT '' COMMENT '客户MDM名称',
  `Fbiz_customer_no` varchar(32) NOT NULL DEFAULT '' COMMENT '业务客户代码',
  `Fbiz_customer_name` varchar(128) NOT NULL DEFAULT '' COMMENT '业务客户名称',
  `Fcountry` varchar(100) NOT NULL DEFAULT '' COMMENT '国别/地区',
  `Fou_id` int(10) NOT NULL DEFAULT '0' COMMENT '我方主体ID',
  `Fou_name` varchar(100) NOT NULL DEFAULT '' COMMENT '我方主体名称',
  `Fspoa_id` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS SPOA ID',
  `Fspoa_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS SPOA名称',
  `Fsett_group` varchar(20) NOT NULL DEFAULT '' COMMENT '结算组ID',
  `Fsett_group_name` varchar(128) DEFAULT '' COMMENT '结算组名称',
  `Fbusi_group` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 业务组ID',
  `Fbusi_group_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 业务组名称',
  `Fdept` varchar(20) NOT NULL DEFAULT '' COMMENT 'BOSS 部门ID',
  `Fdept_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'BOSS 部门名称',
  `Foriginal_currency_type` varchar(20) NOT NULL DEFAULT '' COMMENT '原始币种',
  `Foriginal_income` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '计费金额（原始币种）',
  `Foriginal_tax_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '税率',
  `Foriginal_tax` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '税费（原始币种）',
  `Forigina_work_cost_rate` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '劳务费率',
  `Foriginal_work_cost` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '劳务费（原始币种）',
  `Foriginal_refund` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '退款金额（原始币种）',
  `Foriginal_loss` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '汇率损失（原始币种）',
  `Foriginal_divide` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '分成损失（原始币种）',
  `Foriginal_sett_fee` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '结算金额（原始币种）',
  `Fsettlement_currency_type` varchar(20) NOT NULL DEFAULT '' COMMENT '结算币种',
  `Forigina_settlement_currency_rate` double(20,8) DEFAULT '0.00000000' COMMENT '原始币种转结算币种汇率',
  `Fsettlement_income` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '计费金额（结算币种）)',
  `Fsettlement_work_cost` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT ' 劳务费（结算币种）',
  `Fsettlement_refund` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '退款金额（结算币种）',
  `Fsettlement_loss` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '汇率损失（结算币种）',
  `Fsettlement_divide` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '分成损失（结算币种）',
  `Fsettlement_sett_fee` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '结算金额（结算币种）',
  `Fsettlement_rmb_currency_rate` double(20,8) DEFAULT '0.00000000' COMMENT '入账汇率',
  `Frmb_income` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '计费金额（人民币）',
  `Frmb_work_cost` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '劳务费（人民币）',
  `Frmb_refund` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '退款金额（人民币）',
  `Frmb_loss` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '汇率损失（人民币）',
  `Frmb_divide` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '分成损失（人民币）',
  `Frmb_sett_fee` double(20,4) NOT NULL DEFAULT '0.0000' COMMENT '结算金额（人民币）',
  `Fims_channel_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'IMS渠道ID',
  `Fims_channel_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'IMS渠道',
  `Fims_region` varchar(64) NOT NULL DEFAULT '' COMMENT 'IMS区域',
  `Ffusion_ou_id` varchar(64) NOT NULL DEFAULT '' COMMENT 'FUSION系统OU',
  `Fboss_no` varchar(64) NOT NULL DEFAULT '' COMMENT 'BOSS编号',
  `Fcontract_no` varchar(128) NOT NULL DEFAULT '' COMMENT '合同号',
  `Fmodify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`Fid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;
